print('====== DESAFIO 09 ======')

number_1 = int(input('Digite um número: '))
print('{} x 1 = {}'.format(number_1, number_1 * 1))
print('{} x 2 = {}'.format(number_1, number_1 * 2))
print('{} x 3 = {}'.format(number_1, number_1 * 3))
print('{} x 4 = {}'.format(number_1, number_1 * 4))
print('{} x 5 = {}'.format(number_1, number_1 * 5))
print('{} x 6 = {}'.format(number_1, number_1 * 6))
print('{} x 7 = {}'.format(number_1, number_1 * 7))
print('{} x 8 = {}'.format(number_1, number_1 * 8))
print('{} x 9 = {}'.format(number_1, number_1 * 9))
print('{} x 10 = {}'.format(number_1, number_1 * 10))
print('-'*20)
